### ISSUE TITLE
I am also working on a geom library are you interested in some collaboration?

### ISSUE THREAD

**Issue by nanjizal** [markknol/hx-vector2d#1]
Open to improvements, I am taking inspiration from a number of projects but key feature is that the code needs to be MIT so that it's very compatible with trilateral.

https://github.com/nanjizal/geom

Many aspects are under revision and names adjusted as the approach becomes clearer, and it's very untested currently, I am evolving it to be agnostic incorporating some of the important triangulation aspects, 3D and 2D. Firstly I am looking to get some experiments working prior to perhaps adding inline testing?  It's important that it seems sensible to use.

**Comment by markknol** [comment]
Hey there. Feel free to either use or implement this library in your own code. 
I really like your idea of having one geom library and will keep an eye on it.
